---
- hosts: 192.168.56.104
  become: yes
  tasks:

      - name: Install MariaDB repository 10.3
        apt_repository: repo='deb [arch=amd64] http://mirror.zol.co.zw/mariadb/repo/10.3/ubuntu xenial main' state=present
    
      - name: Install MariaDB Server 10.3
        apt: name=mariadb-server state=latest
        
      - name: Install MariaDB Client 10.3
        apt: name=mariadb-client state=latest

      - name: Restart MariaDB 10.3
        service: name=mysql state=restarted
